# -*- coding: utf-8 -*-
"""rss_scraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uS7JcxCNByf9I0Ga25Td1CvTOFjlPq36
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
from bs4 import BeautifulSoup

URL="https://ipo.einnews.com/rss/cpCdwuL2w4azHHGe"
page=requests.get(URL)
soup=BeautifulSoup(page.content,features='xml')

articles=[]
links=[]
dates=[]
org=[]
for i in range(1,len(soup.find_all('title'))):
  pdd=soup.find_all('title')[i]
  if soup.find_all('title')[i].get_text() not in articles:
    articles.append(soup.find_all('title')[i].get_text())
    links.append(soup.find_all('link')[i].get_text())
    dates.append(soup.find_all('pubDate')[i-1].get_text())
    org.append('ORGS')

df = pd.DataFrame(list(zip(articles,links,dates,org)), 
               columns =['Text', 'Links','Dates','Organization'])

df

import spacy
nlpq = spacy.load('en_core_web_sm')
for i in range(0,df.shape[0]):
  article=df['Text'][i]
  doc=nlpq(article)
  for ele in doc.ents:
    if ele.label_=='ORG':
      df['Organization'][i]=ele
    else:
      df['Organization'][i]="organization not found"

from google.colab import drive
drive.mount('drive')

df.to_csv('rss.csv')
!cp rss.csv "drive/My Drive/"